import './globals.css'
import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'

import { Provider } from '@/app/providers/Provider'

const spaceMono = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`${spaceMono.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
